import { downloads } from '@/lib/config/site';
import { FAQList } from '@/lib/faqsList';
import { FeaturesList } from '@/lib/featuresList';
import { PricingList } from '@/lib/pricingList';
import { contentLocales, defaultLocale } from '@/lib/i18n';
import {
	APP_NAME,
	GITHUB_RELEASES,
	GITHUB_REPO,
	ORG_URL,
	SITE_URL,
	WMS_PRODUCT,
	localeMeta,
	localeUrl,
	seoCopy,
} from '@/lib/seo/site';

const PRODUCT_FACTS = [
	'Product: MetaERP Odoo Client (repository: moco-odoo-client).',
	'Category: mobile ERP client for Odoo, for Android and HarmonyOS (via ZhuoYiTong on HarmonyOS).',
	'Odoo compatibility: Odoo 17 and above, Community and Enterprise editions; Odoo v14 Enterprise is specially supported; Odoo 16 has limited support.',
	'Key capabilities: camera barcode/QR scanning, Bluetooth thermal receipt printing, PDA support, native Android push notifications, AI OCR assistant, multi-account and multi-instance login, on-screen learning mode.',
	'Differences from the official Odoo app: works with the Community edition, supports native mobile messaging inside mainland China, supports direct printing and PDA devices.',
	'Pricing: free for individual users; paid Professional and Premium plans for businesses; OEM white-label branding available on request.',
	'Data handling: the app does not touch or store the business data generated by the connected Odoo instance.',
	'Distribution: signed Android APKs are published at dl.metaerp.ai — an HMS build for Huawei/Honor devices and a GMS build for Google-backed Android devices; the source code is on GitHub.',
	`Related product: ${WMS_PRODUCT.name} (${WMS_PRODUCT.alternateName}) is a mobile warehouse execution system for Odoo from the same vendor, at ${WMS_PRODUCT.url}.`,
];

function normalizeKey(value) {
	return String(value || '').toUpperCase().replace(/-/g, '_');
}

function pick(list, prefix, locale) {
	return list[`${prefix}_${normalizeKey(locale)}`] || [];
}

function bullets(items) {
	return items.map((item) => `- ${item}`).join('\n');
}

/**
 * `llms.txt` — the llmstxt.org style index that answer engines and agents read
 * first. Deliberately short: a summary, the canonical entry points, and facts.
 */
export function buildLlmsTxt() {
	const en = seoCopy[defaultLocale];

	const languageLinks = contentLocales
		.map((locale) => {
			const copy = seoCopy[locale];
			return `- [${localeMeta[locale].label}](${localeUrl(locale)}): ${copy.title} — ${copy.tagline}`;
		})
		.join('\n');

	return `# ${APP_NAME}

> ${en.description}

${APP_NAME} ("Odoo Harmony/Android Client") is a free mobile client application for the Odoo ERP platform, built by ${ORG_URL.replace('https://', '')}. It runs on Android and HarmonyOS and connects to Odoo 17+ Community and Enterprise instances, plus Odoo v14 Enterprise. Individual use is free; businesses can buy Professional/Premium plans or a white-label OEM build. The canonical home page is ${SITE_URL}.

## Key facts

${bullets(PRODUCT_FACTS)}

## Landing pages

${languageLinks}

## Related products

- [${WMS_PRODUCT.name}](${WMS_PRODUCT.url}): mobile warehouse execution system for Odoo running on Android PDA hardware — wave and cluster picking, putaway, cycle counts, packing, package tracking and on-device label printing. Connects directly to Odoo 14-20 with no middleware. Same vendor as ${APP_NAME}.

## Source code and downloads

- [GitHub repository](${GITHUB_REPO}): Kotlin/Jetpack Compose source of the Android client, including the Odoo push-notification module.
- [APK for Huawei / Honor (HMS)](${downloads.hms.url}): signed build using HUAWEI Scan Kit, no Google services required.
- [APK for Google-backed Android (GMS)](${downloads.gms.url}): signed build using Google ML Kit + CameraX.
- [GitHub releases](${GITHUB_RELEASES}): version history and source archives.

## Optional

- [Full content for language models](${SITE_URL}/llms-full.txt): the complete marketing copy, feature list, pricing and FAQ in every supported language.
- [Sitemap](${SITE_URL}/sitemap.xml): all indexable URLs with hreflang alternates.
`;
}

/**
 * `llms-full.txt` — the whole product story, in every locale, in one plain-text
 * document that LLM crawlers can ingest without executing JavaScript.
 */
export function buildLlmsFullTxt() {
	const sections = [];

	sections.push(`# ${APP_NAME} — full content
> ${seoCopy[defaultLocale].description}

Canonical site: ${SITE_URL}
Source code: ${GITHUB_REPO}

## Product facts

${bullets(PRODUCT_FACTS)}`);

	for (const locale of contentLocales) {
		const copy = seoCopy[locale];
		const meta = localeMeta[locale];
		const features = pick(FeaturesList, 'FRETURES', locale);
		const tiers = pick(PricingList, 'PRICING', locale);
		const faqs = pick(FAQList, 'FAQ', locale);

		const parts = [
			`## ${meta.label} (${meta.hreflang}) — ${localeUrl(locale)}`,
			'',
			`Title: ${copy.title}`,
			`Description: ${copy.description}`,
			`Tagline: ${copy.tagline}`,
			'',
			'### Features',
			'',
			features.map((feature) => `- ${feature.title}: ${feature.description}`).join('\n'),
			'',
			'### Pricing',
			'',
			tiers
				.map((tier) => {
					const price = `${tier.price}/${tier.duration}`;
					const details = (tier.features || []).join('; ');
					return `- ${tier.title} (${price}) — ${tier.description}. Includes: ${details}`;
				})
				.join('\n'),
			'',
			'### FAQ',
			'',
			faqs.map((faq) => `Q: ${faq.question}\nA: ${faq.answer}`).join('\n\n'),
		];

		sections.push(parts.join('\n'));
	}

	return `${sections.join('\n\n---\n\n')}\n`;
}
