export const FAQList = {
  FAQ_EN: [
      {
        "question": "What versions of Odoo are supported?",
        "answer": "It supports Odoo community and enterprise editions from version 17 and above, and also specially supports Odoo v14 enterprise edition."
      },
      {
        "question": "What's the difference from the official app?",
        "answer": "The biggest difference is that the official app only supports enterprise editions and does not support using native messages in China."
      },
      {
        "question": "Does it support multi-account login?",
        "answer": "It supports logging in accounts from different Odoo instances, and also supports logging in multiple accounts under the same Odoo instance."
      },
      {
        "question": "Does it support PDA?",
        "answer": "The latest PDA should be able to support. Some old PDA's built-in components may be too old to work properly."
      },
      {
        "question": "We want to access our internal Odoo system, is the production data secure?",
        "answer": "We strictly adhere to the privacy policy, the app will not touch the data generated by Odoo."
      },
      {
        "question": "We are a company using it, how is the fee calculated?",
        "answer": "It is recommended to adopt the OEM form, the name and icon of the app use the company's materials, which is convenient for unified image. The specific OEM fees are shown in the package list."
      },
      {
        "question": "I am an individual user, how is the specific fee calculated?",
        "answer": "Personal use is completely free."
      }
  ],

  FAQ_ZH: [
    {
      question: "支持Odoo的那些版本？",
      answer:
        "支持Odoo v17以上的社区版和企业版（v16有限支持），同时特别支持Odoo v14企业版。",
    },
    {
      question: "是否支持鸿蒙操作系统？",
      answer:
        "在鸿蒙操作系统上通过卓易通支持所有功能正常使用。",
    },
    {
      question: "和官方App有何不同？",
      answer:
        "官方App仅支持企业版，且不支持在国内使用原生消息。官方App不支持直接打印、不支持PDA。",
    },
    {
      question: "支持多账户登录吗？",
      answer:
        "支持不同的Odoo实例的账户登录，也支持同一个Odoo实例下的多个账户登录。",
    },
    {
      question: "支持PDA吗？",
      answer:
        "最新的PDA应该都能支持。部分老PDA的系统内置组件版本过低，可能无法正常使用。推荐idata K3Pro，联系我可获得优惠价格。",
    },
    {
      question: "我们想接入内部的Odoo系统，生产数据安全吗？",
      answer:
        "我们严格遵守隐私条款，App不会触及Odoo产生的数据。",
    },
    {
      question: "我们企业使用，需要费用是怎么算的？",
      answer:
        "建议采用OEM形式，App的名称图标使用企业素材，方便形象统一。具体OEM费用参见套餐列表",
    },
    {
      question: "我是个人用户使用的，具体费用这么算？",
      answer:
        "个人使用完全免费。",
    },
    {
      question: "OEM最终的视觉效果是怎么样的，表现为完全是我们公司的产品吗？",
      answer:
        "是的，Logo和名称以及关于界面等，全部换成贵司的素材，包括链接等。",
    },
    {
      question: "原生的消息通知还需要额外的模块吗？",
      answer:
        "对，需要安装这个模块，然后再配置推送url即可：https://github.com/glovebx/moco-odoo-client/tree/v17/odoo-v17%2B/addons/mail_mobile_push",
    },        
  ],

  FAQ_JA: [
    {
      "question": "Odooのどのバージョンをサポートしていますか？",
      "answer": "Odoo 17 以降のコミュニティ版とエンタープライズ版をサポートしており、特に Odoo v14 エンタープライズ版をサポートしています。"
    },
    {
      "question": "公式アプリとの違いは何ですか？",
      "answer": "公式アプリはエンタープライズ版のみに対応し、国内ではネイティブメッセージの利用がサポートされていない点が最大の違いです。"
    },
    {
      "question": "複数アカウントのログインをサポートしていますか？",
      "answer": "異なる Odoo インスタンスのアカウントのログイン、および同じ Odoo インスタンス内の複数のアカウントのログインをサポートしています。"
    },
    {
      "question": "PDA をサポートしていますか？",
      "answer": "最新の PDA はすべてサポートされているはずです。一部の古い PDA は、システムに組み込まれているコンポーネントのバージョンが低いため、正常に動作しない場合があります。"
    },
    {
      "question": "内部の Odoo システムに接続したいのですが、生産データは安全ですか？",
      "answer": "プライバシーポリシーを厳守しており、アプリは Odoo で生成されたデータにアクセスしません。"
    },
    {
      "question": "企業で使用する場合、料金はどのように計算されますか？",
      "answer": "OEM 方式を採用することをお勧めします。アプリの名前とアイコンに企業の素材を使用することで、イメージを統一できます。OEM 料金の詳細については、プランリストをご覧ください。"
    },
    {
      "question": "個人ユーザーとして使用する場合、料金はどのように計算されますか？",
      "answer": "個人使用は完全に無料です。"
    }
  ],

  FAQ_ES: [
      {
          "question": "¿Qué versiones de Odoo son compatibles?",
          "answer": "Es compatible con las ediciones de la comunidad y de la empresa de Odoo 17 y superiores, y también admite específicamente la edición de la empresa Odoo v14."
      },
      {
          "question": "¿En qué se diferencia de la aplicación oficial?",
          "answer": "La mayor diferencia es que la aplicación oficial solo es compatible con la edición empresarial y no admite el uso de mensajes nativos en China."
      },
      {
          "question": "¿Admite el inicio de sesión de múltiples cuentas?",
          "answer": "Admite el inicio de sesión de cuentas de diferentes instancias de Odoo y también admite el inicio de sesión de múltiples cuentas en la misma instancia de Odoo."
      },
      {
          "question": "¿Admite PDA?",
          "answer": "Los PDA más nuevos deberían ser compatibles. Algunos PDA más antiguos tienen versiones de componentes integrados demasiado bajas y es posible que no funcionen correctamente."
      },
      {
          "question": "Queremos conectarnos a nuestro sistema Odoo interno, ¿son seguros los datos de producción?",
          "answer": "Cumplimos estrictamente con los términos de privacidad, la aplicación no accederá a los datos generados por Odoo."
      },
      {
          "question": "Utilizamos la aplicación en nuestra empresa, ¿cómo se calcula la tarifa?",
          "answer": "Se recomienda utilizar el formato OEM, el nombre y el icono de la aplicación utilizan materiales de la empresa, lo que facilita la unidad de imagen. Para obtener más información sobre las tarifas OEM, consulte la lista de planes."
      },
      {
          "question": "Soy un usuario individual, ¿cómo se calcula la tarifa?",
          "answer": "El uso personal es totalmente gratuito."
      }
  ],

  FAQ_RU: [
      {
        "question": "Какие версии Odoo поддерживаются?",
        "answer": "Поддерживаются версии Odoo 17 и выше для сообщества и предприятий, а также специально поддерживается версия Odoo v14 для предприятий."
      },
      {
        "question": "В чем разница с официальным приложением?",
        "answer": "Основное отличие заключается в том, что официальное приложение поддерживает только версии для предприятий и не поддерживает использование собственных уведомлений в России."
      },
      {
        "question": "Поддерживается ли вход в несколько учетных записей?",
        "answer": "Поддерживается вход в учетные записи разных экземпляров Odoo, а также вход в несколько учетных записей в одном экземпляре Odoo."
      },
      {
        "question": "Поддерживается ли PDA?",
        "answer": "Последние модели PDA должны поддерживаться. Некоторые старые модели PDA могут иметь устаревшие версии встроенных компонентов и не работать правильно."
      },
      {
        "question": "Мы хотим подключиться к внутренней системе Odoo, безопасны ли производственные данные?",
        "answer": "Мы строго соблюдаем политику конфиденциальности, приложение не имеет доступа к данным, созданным в Odoo."
      },
      {
        "question": "Мы используем приложение для бизнеса, как рассчитывается стоимость?",
        "answer": "Рекомендуем использовать OEM-версию, название и значок приложения используют корпоративные материалы для единого имиджа. Стоимость OEM-версии см. в списке пакетов."
      },
      {
        "question": "Я частный пользователь, как рассчитывается стоимость?",
        "answer": "Использование для личных целей абсолютно бесплатно."
      }
  ],
};
